version: "2"

services:
    app-launcher:
        build: .
        environment:
            - JENKINS_URL=${JENKINS_URL}
            - JENKINS_USER=${JENKINS_USER}
            - JENKINS_PASSWORD=${JENKINS_PASSWORD}
        ports:
            - "7373:5000"
